/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author Ryan
 */
public class mainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainJFrame
     */
    public mainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgLogo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imgLogo.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        imgLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/coffee_logo.png"))); // NOI18N

        jButton1.setText("Create/Reset Database");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("The Coffee Shop was founded way back in 2518 when two brothers, John and John, were sitting around not doing anything. Both John and John were playing 'Halo LXIV: The Last Stance' in their mom's basement (her name is Karen) when they suddenly realized .. When the flood comes to invade our planet, the troops are gonna need some coffee to drink. Without hesitation, both John and John jumped at the chance to start their business to hopefully one day meet some troops and possibly even the Master Chief himself. Years later, in 2525, just as they expected, the Flood came to invade Earth. John and John were prepared for the war with serving the troops Coffee. On September 13th of 2526 though, Karen (the brother's mom) came by the store with some awful news. The brother's father had past away, but she had a special mission for the two; They needed to deliver coffee to their long lost brother, also named John. Not just any John, the Master Chief himself. Both John and John were floored by the news of having THE Master Chief as their brother, but accepted the task. Rigorously driving in their Tesla Mk 22, they made it to the Station where Master Chief was expected to land any moment, when a soldier was radioed and told that the Chief had been called on special duty. Both John and John were disappointed, but knew that their brother was doing a great job at fighting the flood. Their admiration for their brother has continued to drive their passion for making great coffee, and is what keeps The Coffee Shop open after all these years.\n");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextArea1);

        jMenu1.setText("File");

        jMenuItem1.setText("Display Coffees");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Display Customers");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Display Orders");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("New Customer");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("New Order");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        menuBar.add(jMenu1);

        jMenu2.setText("Edit");
        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imgLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imgLogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        final String CONN_STRING = "jdbc:derby://localhost:1527/dbCoffeeStoreData";
        try
        {
            Connection conn = DriverManager.getConnection(CONN_STRING, "root", "root");
            Statement comm = conn.createStatement();
            
            //Check if tables exist
            DatabaseMetaData dbMeta = conn.getMetaData();
            ResultSet tableCheck = dbMeta.getTables(null, null, null, new String[] {"TABLE"});
            while (tableCheck.next())
            {
                //if the tables exist, drop them
                if(tableCheck.getString("TABLE_NAME").equals("CUSTOMER"))
                {
                    comm.execute("DROP TABLE customer");
                }
                if(tableCheck.getString("TABLE_NAME").equals("ORDERS"))
                {
                    comm.execute("DROP TABLE orders");
                }
                if(tableCheck.getString("TABLE_NAME").equals("COFFEE"))
                {
                    comm.execute("DROP TABLE coffee");
                }
            }
            tableCheck.close();
            
            //create the tables
            comm.execute("CREATE TABLE customer (\n" +
                         "customerID varchar (30) NOT NULL,\n" +
                         "firstName varchar (30) NOT NULL,\n" +
                         "lastName varchar (30) NOT NULL,\n" +
                         "street varchar (30) NOT NULL,\n" +
                         "city varchar (30) NOT NULL,\n" +
                         "state varchar (30) NOT NULL,\n" +
                         "zip varchar (10) NOT NULL,\n" +
                         "phone varchar (20) NOT NULL,\n" +
                         "email varchar (60) NOT NULL,\n" +
                         "creditLimit DOUBLE NOT NULL,\n" +
                         "PRIMARY KEY (customerID)\n" +
                         ")");
            comm.execute("CREATE TABLE coffee (\n" +
                         "coffeeID varchar (30) NOT NULL,\n" +
                         "coffeeName varchar (30) NOT NULL,\n" +
                         "coffeeDesc varchar (30) NOT NULL,\n" +
                         "numOrdered DOUBLE NOT NULL,\n" +
                         "numStock DOUBLE NOT NULL,\n" +
                         "PRIMARY KEY (coffeeID)\n" +
                         ")");
            comm.execute("CREATE TABLE orders (\n" +
                         "orderID varchar (30) NOT NULL,\n" +
                         "customerID varchar (30) NOT NULL,\n" +
                         "coffeeID varchar (30) NOT NULL,\n" +
                         "numberOrdered DOUBLE NOT NULL,\n" +
                         "total DOUBLE NOT NULL,\n" +
                         "PRIMARY KEY (orderID)\n" +
                         ")");
            
            //create the data for the tables
            //Customers
            comm.execute("INSERT INTO customer VALUES ('123456789', 'John', 'Smith', '123 Fake Street', 'Fakeville', 'Fakes', '27878', '3398789876', 'jSmith6789@mail.com', 50.0)");
            comm.execute("INSERT INTO customer VALUES ('987654321', 'Jane', 'Doe', '568 Fake Street', 'Fakeville', 'Fakes', '27878', '3392348462', 'jDoe4321@mail.com', 40.0)");
            comm.execute("INSERT INTO customer VALUES ('878765652', 'Frank', 'Siracha', '846 Fake Street', 'Fakeville', 'Fakes', '27878', '3397743216', 'fSir2121@mail.com', 25.0)");
            comm.execute("INSERT INTO customer VALUES ('951847362', 'Benita', 'Lopez', '826 Fake Street', 'Fakeville', 'Fakes', '27878', '3392105160', 'bLopez@mail.com', 38.0)");
            comm.execute("INSERT INTO customer VALUES ('326159487', 'Sally', 'May', '123 Fake Street', 'Fakeville', 'Fakes', '27878', '3398798050', 'sMay5454@mail.com', 68.0)");
            //Coffee
            comm.execute("INSERT INTO coffee VALUES ('12345', 'Black Coffee', 'Simple, standard coffee.', 350.0, 700.0)");
            comm.execute("INSERT INTO coffee VALUES ('54321', 'Coffee Cream', 'Standard coffee, with cream', 400.0, 200.0)");
            comm.execute("INSERT INTO coffee VALUES ('78495', 'Latte', 'Foamy Latte', 250.0, 100.0)");
            comm.execute("INSERT INTO coffee VALUES ('32615', 'Cappuccino', 'With fancy tree art', 100.0, 60.0)");
            comm.execute("INSERT INTO coffee VALUES ('15948', 'Afogato', 'Everyone else serves it ..', 25.0, 20.0)");
            //Orders
            comm.execute("INSERT INTO orders VALUES ('523', '123456789', '12345', 1.0, 3.00)");
            comm.execute("INSERT INTO orders VALUES ('524', '987654321', '54321', 2.0, 6.50)");
            comm.execute("INSERT INTO orders VALUES ('525', '123456789', '78495', 1.0, 3.00)");
            comm.execute("INSERT INTO orders VALUES ('526', '878765652', '12345', 2.0, 6.75)");
            comm.execute("INSERT INTO orders VALUES ('527', '951847362', '78495', 1.0, 2.00)");
            comm.execute("INSERT INTO orders VALUES ('528', '123456789', '54321', 4.0, 12.25)");
            comm.execute("INSERT INTO orders VALUES ('529', '878765652', '12345', 2.0, 6.33)");
            comm.execute("INSERT INTO orders VALUES ('530', '951847362', '15948', 2.0, 6.25)");
            comm.execute("INSERT INTO orders VALUES ('531', '326159487', '32615', 1.0, 3.00)");
            comm.execute("INSERT INTO orders VALUES ('532', '326159487', '15948', 3.0, 9.75)");
            
        }
        catch(Exception ex)
        {
            System.out.println("Something broke .. " + ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       customerJFrame customers = new customerJFrame();
       customers.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       coffeeJFrame coffees = new coffeeJFrame();
       coffees.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        ordersJFrame orders = new ordersJFrame();
        orders.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        newCustomerJFrame newCust = new newCustomerJFrame();
        newCust.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        newOrderJFrame newOrder = new newOrderJFrame();
        newOrder.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgLogo;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
}
